language: go
go: 1.6
services: docker

install:
    - if [ ! -d $GOPATH/src/github.com/munnerz ]; then mkdir -p $GOPATH/src/github.com/munnerz; fi
    - if [ "$TRAVIS_REPO_SLUG" != "munnerz/acme-secrets" ]; then ln -s $GOPATH/src/github.com/$TRAVIS_REPO_SLUG $GOPATH/src/github.com/munnerz/acme-secrets; fi

script:
    - CGO_ENABLED=0 go build -a -installsuffix cgo github.com/munnerz/acme-secrets

after_success:
    - if [ "$TRAVIS_BRANCH" = "master"]; then DOCKER_TAG='latest'; else DOCKER_TAG=$TRAVIS_BRANCH; fi
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker build -t $DOCKER_IMAGE:$DOCKER_TAG .; fi
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USER" -p "$DOCKER_PASS"; fi
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push $DOCKER_IMAGE:$DOCKER_TAG; fi

