language: go
go: 1.6
services: docker

install:
    - if [ ! -d $GOPATH/src/github.com/munnerz ]; then mkdir -p $GOPATH/src/github.com/munnerz; fi
    - if [ "$TRAVIS_REPO_SLUG" != "munnerz/kube-acme" ]; then ln -s $GOPATH/src/github.com/$TRAVIS_REPO_SLUG $GOPATH/src/github.com/munnerz/kube-acme; fi

script:
    - CGO_ENABLED=0 go build -a -installsuffix cgo github.com/munnerz/kube-acme

after_success:
    - if [ -z "$DOCKER_IMAGE" ]; then DOCKER_IMAGE='munnerz/kube-acme'; fi
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then docker build -t $DOCKER_IMAGE:latest .; fi
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USER" -p "$DOCKER_PASS"; fi
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push $DOCKER_IMAGE:latest; fi
